### ISSUE TITLE
When code will be released?

### ISSUE THREAD

**Issue by Nestart** [xinshuoweng/mono3D_PLiDAR#1]
I am very interested in the integration of this work with AB3DMOT, so I would like to know when this code will be released?
In addition, I would like to know whether this code contains the whole pipeline from the Pseudo-LiDAR generation to the object detection?

**Comment by xinshuoweng** [comment]
Thanks for your interest. I will try my best. But I guess at least 2 weeks from now for this repo.

Yes. Hopefully, we will integrate and release all the stuff we have in the next coming year. It will include results from not only KITTI datasets but also other new datasets. On the other hand, it will have not only detection but tracking and forecasting. Please stay tuned.

**Comment by Nestart** [comment]
Thanks for your sharing.
Looking forward to your work.
